# generated by datamodel-codegen:
#   filename:  PlantBreedingAPI-BrAPI-Germplasm-2.0-resolved.json
#   timestamp: 2021-09-15T18:07:14+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
