#docker-compose.yaml
version: "3.4"
services:
  # redis:
  #   image: redis:latest
  #   hostname: redis
  
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
  
  api:
    build:
      context: ./af-jobs-api
      dockerfile: Dockerfile
    working_dir: /app
    command: ["./gunicorn.sh"]
    environment:
      - C_FORCE_ROOT=true
      - BROKER=amqp://admin:mypass@rabbitmq:5672
    ports:
      - "5000:5000"

    depends_on:
      - rabbitmq
  
  worker:
    build:
      context: ./af-task-orchestrator
      dockerfile: Dockerfile
    working_dir: /app
    command: ["celery", "-A", "orchestrator.app", "worker", "--pool=gevent", "--concurrency=20", "-l", "debug" ]
    environment:
      - C_FORCE_ROOT=true
      - BROKER=amqp://admin:mypass@rabbitmq:5672
      - BACKEND=rpc://
      - CONSUMER_QUEUE=jobs
      - B4R_API_BASE_URL=https://b4rapi-uat.ebsproject.org/v3/
      - B4R_API_TOKEN=
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  # beat:
  #   build:
  #     context: ./orchestrator
  #     dockerfile: Dockerfile
  #   image: *img
  #   command: [celery, beat, --app=worker.app, --loglevel=INFO]
  #   depends_on:
  #     - rabbitmq
  #   restart: 'no'
  #   volumes:
  #     - ./app:/app
      
  