#docker-compose.yaml
version: "3.4"
services:
  # redis:
  #   image: redis:latest
  #   hostname: redis
  
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
  
  api:
    build:
      context: ./af-jobs-api
      dockerfile: Dockerfile
    working_dir: /app
    command: ["./gunicorn.sh"]
    environment:
      - CONSUMER_QUEUE=jobs
      - MQ_EXCHANGE=
      - MQ_HOST=rabbitmq
      - MQ_PORT=5672
      - MQ_USER=admin
      - MQ_PASS=mypass
    ports:
      - "5000:5000"

    depends_on:
      - rabbitmq
  
  worker:
    build:
      context: ./af-task-orchestrator
      dockerfile: Dockerfile
    working_dir: /app
    command: ["celery", "-A", "orchestrator.app", "worker", "--pool=gevent", "--concurrency=20", "-l", "debug" ]
    environment:
      - BROKER=amqp://admin:mypass@rabbitmq:5672
      - BACKEND=rpc://
      - CONSUMER_QUEUE=jobs
      - B4R_API_BASE_URL=
      - B4R_API_TOKEN=
      - EBS_API_BASE_URL=https://b4rapi-uat.ebsproject.org/v3/
      - EBS_API_TOKEN=eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoickNkR3RjSVh1bHdNUWpDVms2a0NZZyIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL3VzZXJuYW1lIjoiMTA4OTQyNzQyODI2NzExNDc0MjQ0Iiwic3ViIjoiMTA4OTQyNzQyODI2NzExNDc0MjQ0QGNhcmJvbi5zdXBlciIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL3Bob3RvdXJsIjoiaHR0cHM6XC9cL2xoNC5nb29nbGV1c2VyY29udGVudC5jb21cLy1IbW1KQkxGZGNmQVwvQUFBQUFBQUFBQUlcL0FBQUFBQUFBQUFBXC9BTVp1dWNsX3JZN1BEUElOellnQ2EyNnYxWXpHdUh6WWRnXC9zOTYtY1wvcGhvdG8uanBnIiwiYW1yIjpbIlNBTUxTU09BdXRoZW50aWNhdG9yIl0sImlzcyI6Imh0dHBzOlwvXC9zZzEuY2ltbXl0Lm9yZzo5NDQzXC9vYXV0aDJcL3Rva2VuIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvZ2l2ZW5uYW1lIjoiVmlzaG51IiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvaWRlbnRpdHlcL2VtYWlsVmVyaWZpZWQiOiJ0cnVlIiwiYXVkIjoiOWR1d2Vsd0dVOGNLelhBeTJfZ3VWUjloV3U4YSIsImNfaGFzaCI6IlhKTGlJSjc5N1dHb3FQOU5tV1NVMkEiLCJuYmYiOjE2MTc4ODc0ODcsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2xvY2FsIjoiZW4iLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9mdWxsbmFtZSI6IlZpc2hudSBHb3ZpbmRhcmFqIiwiYXpwIjoiOWR1d2Vsd0dVOGNLelhBeTJfZ3VWUjloV3U4YSIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2VtYWlsYWRkcmVzcyI6InZnMjQ5QGNvcm5lbGwuZWR1IiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvbGFzdG5hbWUiOiJHb3ZpbmRhcmFqIiwiZXhwIjoxNjE3ODkxMDg3LCJpYXQiOjE2MTc4ODc0ODd9.ZkEFj_oOYOJNU50XCeP-g_wDWQruX-vocavijmG4LmuBABZuKDqjt4hJseI2yvBV6D4Y-u7R-NQYj5IiiBkkaQZu3Xq_4Elv05NNmRy9WxvvZIiyH1omT7SxFf614Lv2AhYrK68s7OAu2ymhxW0dZ6WNHgFhimm3fWSZjZ0DRLjJ_k02zqq9ScS6GuAFNL8rwMmqay4ipFEv7e8qPWt5otoDM8vF5b-LEnW_PL6iPH4tP7o8j2a_4PS8JCzeUDpsfUFHcJr0C1vHFczg--oIfDu6bNUlM5ZpSMeRyXF70dmf9PkuwT1Hu59904AGKq-IA4GesOfMcKN8Eu9OpPfDGg
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  # beat:
  #   build:
  #     context: ./orchestrator
  #     dockerfile: Dockerfile
  #   image: *img
  #   command: [celery, beat, --app=worker.app, --loglevel=INFO]
  #   depends_on:
  #     - rabbitmq
  #   restart: 'no'
  #   volumes:
  #     - ./app:/app
      
  