#! /usr/local/bin/python

import docker
import sys

file1 = sys.argv[1]
file2 = sys.argv[2]
cmd = f'/bin/bash -c "asreml /home/asreml/inputs/{file1} /home/asreml/inputs/file2"'
client = docker.DockerClient(base_url='unix://var/run/docker.sock')
output = client.containers.run(
    "ebsproject/ba-asreml:21.05",
    command=cmd,
    volumes={
        'asreml_license_dir': {"bind": '/home/asreml/licenses', "mode": "rw"},
        'asreml_inputs_dir': {"bind": '/home/asreml/inputs', "mode": "rw"},
        'asreml_outputs_dir': {"bind": '/home/asreml/outputs', "mode": "rw"},
    },
    stderr=True, 
)
print(str(output))
